SELECT CAR.CAR_ID, CAR.CAR_TYPE, FLOOR((1 - PLAN.DISCOUNT_RATE / 100) * CAR.DAILY_FEE * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
    ON CAR.CAR_TYPE = PLAN.CAR_TYPE AND PLAN.DURATION_TYPE LIKE '30%'
WHERE CAR.CAR_ID NOT IN (SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
    AND CAR.CAR_TYPE IN ('세단', 'SUV')
    AND FLOOR((1 - PLAN.DISCOUNT_RATE / 100) * CAR.DAILY_FEE * 30) BETWEEN 500000 AND 2000000 - 1
ORDER BY FEE DESC, CAR.CAR_TYPE, CAR.CAR_ID DESC
    