SELECT A.MEMBER_NAME, B.REVIEW_TEXT, B.REVIEW_DATE
FROM MEMBER_PROFILE AS A
JOIN (SELECT R.MEMBER_ID, R.REVIEW_TEXT, R.REVIEW_DATE, RANK() OVER (ORDER BY S.COUNTS DESC) AS RANKS
FROM REST_REVIEW AS R
    JOIN (SELECT MEMBER_ID, COUNT(MEMBER_ID) AS COUNTS
    FROM REST_REVIEW
    GROUP BY MEMBER_ID) AS S
    ON R.MEMBER_ID = S.MEMBER_ID) AS B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE RANKS = 1
ORDER BY B.REVIEW_DATE