SELECT C.FLAVOR
FROM (SELECT A.FLAVOR, (A.SUM_FIRST_HALF + B.SUM_JULY) AS TOTAL
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_FIRST_HALF
FROM FIRST_HALF
GROUP BY FLAVOR) AS A
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_JULY
FROM JULY
GROUP BY FLAVOR) AS B
ON A.FLAVOR = B.FLAVOR
ORDER BY TOTAL DESC
LIMIT 3) AS C