SELECT *
FROM (SELECT A.WRITER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID AND A.STATUS = 'DONE'
GROUP BY A.WRITER_ID
ORDER BY TOTAL_SALES) C
WHERE C.TOTAL_SALES >= 700000